# Generated by Django 4.1 on 2022-09-04 19:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reporter",
            fields=[
                ("reporter_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reporter_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scammer",
            fields=[
                ("scammer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "scammer_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "reporter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="S_reporter_id",
                        to="dashboard.reporter",
                    ),
                ),
            ],
            options={"unique_together": {("reporter_id", "scammer_number")},},
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                ("info_id", models.AutoField(primary_key=True, serialize=False)),
                ("contained_sms", models.TextField()),
                ("sms_date", models.DateField()),
                ("sms_time", models.TimeField()),
                ("date_reported", models.DateField(auto_now_add=True)),
                ("time_reported", models.TimeField(auto_now_add=True)),
                (
                    "reporter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="r_reporter_id",
                        to="dashboard.reporter",
                    ),
                ),
                (
                    "scammer_number",
                    models.ManyToManyField(
                        related_name="r_scammer_number", to="dashboard.scammer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "phone_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="phone_number",
                        serialize=False,
                        to="dashboard.reporter",
                    ),
                ),
                ("reg_name", models.CharField(max_length=200)),
                ("reg_date_time", models.DateTimeField()),
                (
                    "reg_status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Imesajiliwa"),
                            ("NOT_REGISTERED", "Haijasajiliwa"),
                        ],
                        default="Inachakatwa",
                        max_length=18,
                    ),
                ),
                ("location", models.TextField()),
                (
                    "scammer_id2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scammer_id2",
                        to="dashboard.scammer",
                    ),
                ),
            ],
        ),
    ]
